# Generated by Django 6.0.3 on 2026-03-06 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoObrigatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=100)),
                ('cbo', models.CharField(blank=True, max_length=10)),
                ('quantidade_minima', models.PositiveIntegerField()),
                ('is_critico', models.BooleanField(default=False, help_text='Cargo crítico paralisa a obra se estiver em déficit', verbose_name='Cargo Crítico')),
                ('requer_habilitacao', models.BooleanField(default=False)),
                ('habilitacao_descricao', models.CharField(blank=True, max_length=200)),
                ('observacao', models.TextField(blank=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_obrigatorios', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Cargo Obrigatório',
                'verbose_name_plural': 'Cargos Obrigatórios',
            },
        ),
        migrations.CreateModel(
            name='ColaboradorMobilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('matricula_empresa', models.CharField(blank=True, max_length=30)),
                ('funcao', models.CharField(max_length=100)),
                ('data_mobilizacao', models.DateField()),
                ('data_desmobilizacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('mobilizado', 'Mobilizado — Ativo'), ('afastado', 'Afastado — Temporário'), ('ferias', 'Férias'), ('desmobilizado', 'Desmobilizado'), ('substituicao', 'Em Processo de Substituição')], default='mobilizado', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('cargo_obrigatorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='mobilizacao.cargoobrigatorio')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Colaborador Mobilizado',
                'verbose_name_plural': 'Colaboradores Mobilizados',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Habilitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('numero_registro', models.CharField(blank=True, max_length=100)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, upload_to='habilitacoes/')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilitacoes', to='mobilizacao.colaboradormobilizado')),
            ],
            options={
                'verbose_name': 'Habilitação',
                'verbose_name_plural': 'Habilitações',
            },
        ),
    ]
