# Generated by Django 6.0.3 on 2026-03-06 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField()),
                ('categoria', models.CharField(choices=[('mao_de_obra', 'Mão de Obra'), ('equipamentos', 'Equipamentos'), ('materiais', 'Materiais'), ('subcontratados', 'Subcontratados'), ('administrativo', 'Administrativo'), ('outros', 'Outros')], max_length=20)),
                ('subcategoria', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('fornecedor', models.CharField(blank=True, max_length=200)),
                ('numero_nf_fornecedor', models.CharField(blank=True, max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo', models.CharField(choices=[('realizado', 'Realizado'), ('provisionado', 'Provisionado')], default='realizado', max_length=15)),
                ('data_lancamento', models.DateField()),
                ('comprovante', models.FileField(blank=True, upload_to='gastos/')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='contratos.contrato')),
                ('lancado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto Operacional',
                'verbose_name_plural': 'Gastos Operacionais',
                'ordering': ['-competencia', '-data_lancamento'],
            },
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('competencia', models.DateField()),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_glosa', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_retencao', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('elaboracao', 'Em Elaboração'), ('submetida', 'Submetida à Vale'), ('em_analise', 'Em Análise'), ('aprovada', 'Aprovada'), ('glosada', 'Aprovada com Glosa'), ('rejeitada', 'Rejeitada'), ('nf_emitida', 'Nota Fiscal Emitida'), ('paga', 'Paga')], default='elaboracao', max_length=20)),
                ('data_submissao', models.DateField(blank=True, null=True)),
                ('data_aprovacao', models.DateField(blank=True, null=True)),
                ('data_emissao_nf', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('data_previsao_pagamento', models.DateField(blank=True, null=True)),
                ('numero_nf', models.CharField(blank=True, max_length=20)),
                ('justificativa_glosa', models.TextField(blank=True)),
                ('documento', models.FileField(blank=True, upload_to='medicoes/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicoes', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Medição',
                'verbose_name_plural': 'Medições',
                'ordering': ['-competencia', '-numero'],
                'unique_together': {('contrato', 'numero')},
            },
        ),
    ]
