# Generated by Django 6.0.3 on 2026-03-06 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sap', models.CharField(max_length=20, unique=True)),
                ('objeto', models.TextField()),
                ('area', models.CharField(choices=[('mineracao', 'Mineração'), ('logistica', 'Logística'), ('energia', 'Energia'), ('engenharia', 'Engenharia')], max_length=20)),
                ('modalidade', models.CharField(choices=[('servico', 'Prestação de Serviço'), ('fornecimento', 'Fornecimento'), ('misto', 'Misto')], max_length=20)),
                ('status', models.CharField(choices=[('minuta', 'Minuta'), ('aprovacao', 'Em Aprovação'), ('vigente', 'Vigente'), ('suspenso', 'Suspenso'), ('encerrado', 'Encerrado')], default='minuta', max_length=20)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_atual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_assinatura', models.DateField()),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('data_termino_atual', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='empresas.empresa')),
                ('gestor_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_admin', to=settings.AUTH_USER_MODEL)),
                ('gestor_tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_tecnicos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemEscopo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('unidade', models.CharField(max_length=30)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Item de Escopo',
                'verbose_name_plural': 'Itens de Escopo',
            },
        ),
        migrations.CreateModel(
            name='Aditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('prazo', 'Prazo'), ('valor', 'Valor'), ('prazo_valor', 'Prazo e Valor')], max_length=20)),
                ('nova_data_termino', models.DateField(blank=True, null=True)),
                ('valor_acrescimo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('justificativa', models.TextField()),
                ('data_assinatura', models.DateField()),
                ('documento', models.FileField(blank=True, upload_to='aditivos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Aditivo',
                'verbose_name_plural': 'Aditivos',
                'ordering': ['numero'],
                'unique_together': {('contrato', 'numero')},
            },
        ),
    ]
